# Generated by Django 2.0.6 on 2020-03-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss_show', '0002_auto_20200308_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuser',
            name='space',
        ),
        migrations.AddField(
            model_name='tpicture',
            name='datetime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tuser',
            name='address_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tuser',
            name='regist_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tuser',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
