import datetime
now = datetime.datetime.now().date()
print(now)
week1 = now - datetime.timedelta(weeks=1)
week2 = now - datetime.timedelta(weeks=2)
week3 = now - datetime.timedelta(weeks=3)
week4 = now - datetime.timedelta(weeks=4)
week5 = now - datetime.timedelta(weeks=5)
week6 = now - datetime.timedelta(weeks=6)
print(week1)
print(week2)
print(week3)
print(week4)
print(week5)
print(week6)