# Generated by Django 2.0.6 on 2020-03-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss_article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='datatime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
